- name: GitSync: Sync GitHub and Azure DevOps activities
  uses: a11smiles/GitSync@v1.2.1

name: Sync with Azure DevOps

on:
  schedule:
    - cron: '*/15 * * * *'
  issues:
    types: [opened, closed, deleted, reopened, edited, labeled, unlabeled, assigned, unassigned]
  issue_comment:
    types: [created]

jobs:
  alert:
    runs-on: ubuntu-latest
    name: Sync workflow
    steps:       
    - uses: actions/checkout@v3
    - uses: a11smiles/GitSync@main
      env:     
        ado_token: '${{ secrets.ADO_PERSONAL_ACCESS_TOKEN }}'
        github_token: '${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}'
        config_file: './.github/workflows/sync_config.json'
        
        name: "GitSync: Sync GitHub and Azure DevOps activities"
description: "A workflow action that syncs GitHub and Azure DevOps activities."
author: "a11smiles"
branding: 
  icon: "repeat"
  color: "blue"
runs:
  using: "node16"
  main: "index.js"  
inputs:
  ado:
    description: "An alternate Azure DevOps configuration from GitHub secrets"
    required: false
  github:
    description: "An alternate GitHub configuration from GitHub secrets"
    required: false
    
    
